name: Lint code

on: [push, pull_request]

jobs:
  lint:
    runs-on: ubuntu-20.04
    timeout-minutes: 10

    steps:
    - uses: actions/checkout@v3
    
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: "3.10"
    
    - name: Install Poetry
      run: |
        curl -sSL https://install.python-poetry.org | POETRY_HOME="$GITHUB_WORKSPACE/poetry" python -
        echo "$GITHUB_WORKSPACE/poetry/bin" >> $GITHUB_PATH

    - name: Install project
      working-directory: ./
      run: poetry install --no-interaction

    - name: Lint code
      working-directory: ./
      run: |
        poetry run black .
        poetry run pflake8 .
        poetry run isort .
        poetry run pylint .
        poetry run mypy .
    