name: Lint code

on: [push, pull_request]

jobs:
  lint:
    runs-on: ubuntu-20.04
    timeout-minutes: 10

    steps:
    - uses: actions/checkout@v3
    
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: "3.10"
    
    - name: Install Poetry
      uses: snok/install-poetry@v1
      with:
        virtualenvs-create: true
        virtualenvs-in-project: true
        installer-parallel: true

    - name: Install project
      working-directory: ./
      run: poetry install --no-interaction

    - name: Lint code
      working-directory: ./
      run: |
        poetry run black .
        poetry run pflake8 .
        poetry run isort .
        poetry run pylint .
        poetry run mypy .
    